# Generated by Django 5.0.6 on 2024-07-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(blank=True, choices=[('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('Beauty', 'Beauty'), ('Grocery', 'Grocery'), ('Health & Wellness', 'Health & Wellness'), ('Baby', 'Baby'), ('Pet', 'Pet'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Tools & Hardware', 'Tools & Hardware'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
